mybatis:
  mapperLocations: classpath:mybatis/*-mapper.xml
  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: com.wei
  checkConfigLocation: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books?serverTimezone=UTC&useSSL=false
    username: root
    password: wei
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8091
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8